/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_carrero_sisiruca_edd_secc2;

import static proyecto_carrero_sisiruca_edd_secc2.PanelMenu.grafo;
import javax.swing.JOptionPane;

/**
 *
 * @author Angel Carrero
 */
public class Editargrafo extends javax.swing.JFrame {

    private txt archivo = new txt();
    static Grafo grafo;

    /**
     * Creates new form OptionSelection
     */
    public Editargrafo(Grafo grafo) {
        initComponents();
        this.grafo = grafo;
        setLocationRelativeTo(null);

        Usuario pointer = grafo.getList().getUhead();

        while (pointer != null) {
            //recorre el grafo con un nodo aux pointer y se agregan las opciones en el jcombobox
            option1.addItem(pointer.getName());
            option2.addItem(pointer.getName());

            pointer = pointer.getNext();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        show = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();
        input = new javax.swing.JTextField();
        option1 = new javax.swing.JComboBox<>();
        option2 = new javax.swing.JComboBox<>();
        adybutton = new javax.swing.JButton();
        addnodo = new javax.swing.JButton();
        inputnodo = new javax.swing.JTextField();
        salir = new javax.swing.JButton();
        input1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        jLabel1.setText("ID num");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 60, 20));

        show.setText("Mostrar Adyacencias");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        jPanel1.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        output.setColumns(20);
        output.setRows(5);
        jScrollPane1.setViewportView(output);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 290, 220));

        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });
        jPanel1.add(input, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 50, -1));

        option1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option1ActionPerformed(evt);
            }
        });
        jPanel1.add(option1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 110, 20));

        option2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option2ActionPerformed(evt);
            }
        });
        jPanel1.add(option2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 110, 20));

        adybutton.setText("Agregar Adyacencia");
        adybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adybuttonActionPerformed(evt);
            }
        });
        jPanel1.add(adybutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        addnodo.setText("Agregar Usuario");
        addnodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnodoActionPerformed(evt);
            }
        });
        jPanel1.add(addnodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        inputnodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputnodoActionPerformed(evt);
            }
        });
        jPanel1.add(inputnodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 90, -1));

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jPanel1.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, -1, -1));

        input1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input1ActionPerformed(evt);
            }
        });
        jPanel1.add(input1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 50, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel2.setText("RedGrafo Usuarios");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 140, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 8)); // NOI18N
        jLabel3.setText("y presione \"Agregar Usuario\"");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 130, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        jLabel4.setText("User name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 90, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 8)); // NOI18N
        jLabel5.setText("Presione para crear Adyacencia");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 160, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 8)); // NOI18N
        jLabel6.setText("Rellene los campos ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 110, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 8)); // NOI18N
        jLabel7.setText("Usuario 1");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 110, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 8)); // NOI18N
        jLabel8.setText("Usuario 2");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 110, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 8)); // NOI18N
        jLabel9.setText("Peso");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 50, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 8)); // NOI18N
        jLabel10.setText("Seleccione en los campos:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 120, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        output.setText(grafo.printAdy());
    }//GEN-LAST:event_showActionPerformed

    private void option1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option1ActionPerformed
    }//GEN-LAST:event_option1ActionPerformed

    private void option2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option2ActionPerformed
    }//GEN-LAST:event_option2ActionPerformed

    private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed
    }//GEN-LAST:event_inputActionPerformed

    private void adybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adybuttonActionPerformed
        //inicialización de variables
        String mensaje1 = "";
        String mensaje2 = "";
        String number = "";

        mensaje1 = option1.getSelectedItem().toString();
        mensaje2 = option2.getSelectedItem().toString();
        number = input.getText();

        //Confirmar que es número
        boolean value = false;
        try {
            Integer.parseInt(number);
            value = true;
        } catch (Exception e) {
            value = false;
            JOptionPane.showMessageDialog(null, "El valor que ingresa no es numérico");
        }
        //verificar que el número es un int distinto de 0
        if (mensaje1.equals(mensaje2) || number.equals("0") || number.equals(" ") || number.equals("") || value == false) {
            JOptionPane.showMessageDialog(null, "No se puede hacer esa adyacencia");
            //si es un string o un 0, recarga la ventana
            Editargrafo window2 = new Editargrafo(grafo);
            window2.show();
            this.dispose();
        } else {
            //si sí es int distinto de 0, crea una ady, muestra la nueva ady en el grafo y vacía el input
            grafo.newArco(grafo.returnUsuariobyname(mensaje1), grafo.returnUsuariobyname(mensaje2), Integer.parseInt(number));
            JOptionPane.showMessageDialog(null, "Adyacencia hecha");
            output.setText(grafo.printAdy());
            input.setText("");

        }


    }//GEN-LAST:event_adybuttonActionPerformed

    private void addnodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnodoActionPerformed
        try {

            //inicialización de variables
            String name = inputnodo.getText();
            String number = "";
            number = input1.getText();
            Usuario aux = grafo.getList().getUhead();
            boolean value = true;
            //verifica con un for si el nuevo nodo está creado, si está creado, value va a ser=false y no va a poder continuar la operación
            //hasta que se vuelva a meter otro name
            for (int i = 0; i < grafo.getNumVerts(); i++) {
                if (aux.getName().toLowerCase().equals(name.toLowerCase())) {
                    JOptionPane.showMessageDialog(null, "Ese Usuario ya está creado");
                    inputnodo.setText("");
                    value = false;
                    break;
                }
                aux = aux.getNext();
            }
            //Confirmar que es número
            boolean value2 = false;
            try {
                Integer.parseInt(number);
                value2 = true;
            } catch (Exception e) {
                value2 = false;
                JOptionPane.showMessageDialog(null, "El valor que ingresa no es numérico");
            }
            //verificar que el número es un int distinto de 0
            if (number.equals("0") || number.equals(" ") || number.equals("") || value == false) {
                JOptionPane.showMessageDialog(null, "No se puede hacer esa adyacencia");
                //si es un string o un 0, recarga la ventana
                Editargrafo window2 = new Editargrafo(grafo);
                window2.show();
                this.dispose();
            }
            if (value == true) {
                //agrega el nuevo nodo y se imprime
                grafo.aumentarVerticesInsertar(name, Integer.parseInt(number));
                output.setText(grafo.printAdy());
                //se agrega en los correspondidos jcombobox
                option1.addItem(name);
                option2.addItem(name);
                inputnodo.setText("");

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error");
        }


    }//GEN-LAST:event_addnodoActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        //cierra y abre la sig ventana
        PanelMenu window = new PanelMenu();
        window.setGrafo(grafo);
        window.setMostrarGrafo(grafo);
        window.show();
        this.dispose();

    }//GEN-LAST:event_salirActionPerformed

    private void inputnodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputnodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputnodoActionPerformed

    private void input1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editargrafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editargrafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editargrafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editargrafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editargrafo(grafo).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addnodo;
    private javax.swing.JButton adybutton;
    private javax.swing.JTextField input;
    private javax.swing.JTextField input1;
    private javax.swing.JTextField inputnodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> option1;
    private javax.swing.JComboBox<String> option2;
    private javax.swing.JTextArea output;
    private javax.swing.JButton salir;
    private javax.swing.JButton show;
    // End of variables declaration//GEN-END:variables
}
