/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_carrero_sisiruca_edd_secc2;

/**
 *
 * @author sisir
 */
public class Seleccion extends javax.swing.JFrame {

    /**
     * Creates new form Seleccion
     */
    public Seleccion() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BoxSeleccion = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        seleccionAfirmativa = new javax.swing.JButton();
        CancelarSelecion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BoxSeleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(BFS) Recorrido en Anchura", "(DFS) Recorrido en Profundidad" }));
        BoxSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxSeleccionActionPerformed(evt);
            }
        });

        jLabel1.setText("Selecciona una opción");

        seleccionAfirmativa.setBackground(new java.awt.Color(0, 204, 204));
        seleccionAfirmativa.setForeground(new java.awt.Color(0, 0, 0));
        seleccionAfirmativa.setText("Aceptar");
        seleccionAfirmativa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionAfirmativaActionPerformed(evt);
            }
        });

        CancelarSelecion.setBackground(new java.awt.Color(0, 204, 204));
        CancelarSelecion.setForeground(new java.awt.Color(0, 0, 0));
        CancelarSelecion.setText("Cancelar");
        CancelarSelecion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarSelecionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BoxSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(seleccionAfirmativa, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CancelarSelecion, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(BoxSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelarSelecion)
                    .addComponent(seleccionAfirmativa))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoxSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxSeleccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxSeleccionActionPerformed

    private void seleccionAfirmativaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionAfirmativaActionPerformed
        // TODO add your handling code here:

        String seleccion = (String) BoxSeleccion.getSelectedItem();

        if (seleccion.equalsIgnoreCase("(BFS) Recorrido en Anchura")) {
            new MostrarBFS().setVisible(true);
        }

        else if (seleccion.equalsIgnoreCase("(DFS) Recorrido en Profundidad")) {
            new MostrarDFS().setVisible(true);
        }

        PanelMenu.menu.setVisible(false);
        dispose();
    }//GEN-LAST:event_seleccionAfirmativaActionPerformed

    private void CancelarSelecionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarSelecionActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_CancelarSelecionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seleccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JComboBox<String> BoxSeleccion;
    private javax.swing.JButton CancelarSelecion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton seleccionAfirmativa;
    // End of variables declaration//GEN-END:variables
}
